# Generated by Django 4.1.1 on 2022-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSEN', '0002_remove_dosen_alamat_remove_dosen_ttl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='jabatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nidn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
